[package]
name = "find_input"
version = "0.1.0"
authors = ["ctfhacker <cld251@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
rayon = "1.3.0"
noodle = { path = "../shared/noodle" }
