[package]
name = "corpgen"
version = "0.1.0"
authors = ["rando"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noodle = { path = "../shared/noodle" }
